--liquibase formatted sql
--changeset casoc:001
CREATE TABLE users
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL,
enabled VARCHAR(1) NOT NULL,
PRIMARY KEY(id)
);
--rollback DROP TABLE users;
