--liquibase formatted sql
--changeset casoc:003
CREATE TABLE user_authority(
id INTEGER GENERATED BY DEFAULT AS IDENTITY,
user_id INTEGER NOT NULL,
authority_id INTEGER NOT NULL,
PRIMARY KEY(id)
)
--rollback DROP TABLE user_authority;